### ISSUE TITLE
Questions about README and Requirements

### ISSUE THREAD

**Issue by i-am-harveyt** [yushinliou/foodDelivery_crawler#1]
1. The script to run seems like `bash run.sh` instead of `bash foodDelievery.py`
2. It seems like there is a module `upoload` is needed but not in the `requirements.txt`

**Comment by yushinliou** [comment]
1. yes, you are right
2. That one is because I used to try to add an auto-upload feature but haven't finished, you are right, please remove it.

**Comment by i-am-harveyt** [comment]
I see, thank you so much
